<h2 class="flex flex-row flex-nowrap items-center mt-16 uppercase">
    <span class="flex-grow block border-t border-purple-700"></span>
    <span class="flex-none block mx-4 px-4 py-2.5 text-xl rounded leading-none font-medium bg-gray-900 text-white">
        List of Tasks
    </span>
    <span class="flex-grow block border-t border-purple-700"></span>
</h2>

<div class="relative overflow-x-auto shadow-md sm:rounded-lg border-2 border-purple-700 mt-16">
    <table class="w-full text-sm text-left rtl:text-right text-gray-400">
        <thead class="text-xs text-gray-200 uppercase bg-gray-700">
            <tr>
                <th scope="col" class="px-6 py-3">ID</th>
                <th scope="col" class="px-6 py-3">Name</th>
                <th scope="col" class="px-6 py-3">Status</th>
                <th scope="col" class="px-6 py-3">Start Time</th>
                <th scope="col" class="px-6 py-3">Finish Time</th>
                <th scope="col" class="px-6 py-3">User</th>
                <th scope="col" class="px-6 py-3">Update</th>
                <th scope="col" class="px-6 py-3">Delete</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->message as $task) { ?>
                <tr class="odd:bg-gray-900 even:bg-gray-800 border-b border-gray-700 hover:bg-gray-600">
                    <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                        <?php echo $task['id'] ?>
                    </th>
                    <td class="px-6 py-4">
                        <?php echo $task['name'] ?>
                    </td>
                    <td class="px-6 py-4">
                        <?php echo $task['status'] ?>
                    </td>
                    <td class="px-6 py-4">
                        <?php $date = new DateTime($task['dateTimeStarted']);
                        echo $date->format('d-m-Y H:i'); ?>
                    </td>
                    <td class="px-6 py-4">
                        <?php if ($task['dateTimeFinished'] !== null) {
                            $date = new DateTime($task['dateTimeFinished']);
                            echo $date->format('d-m-Y H:i');
                        } else {
                            echo 'N/A';
                        } ?>
                    </td>
                    <td class="px-6 py-4">
                        <?php echo $task['user'] ?>
                    </td>
                    <!-- Update Task button -->
                    <td class="px-6 py-4">
                        <form action='update' method='get'>
                            <input type='hidden' name='id' value='<?php echo $task['id']; ?>'>
                            <input type='submit' value='Update' class="bg-purple-700 hover:bg-purple-900 text-white py-2 px-3 rounded cursor-pointer">
                        </form>
                    </td>
                    <!-- Delete Task button -->
                    <td class="px-6 py-4">
                        <form action='delete' method='get'>
                            <input type='hidden' name='id' value='<?php echo $task['id']; ?>'>
                            <input type='submit' value='Delete' class="bg-red-700 hover:bg-red-900 text-white py-2 px-3 rounded cursor-pointer">
                        </form>
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>

<div class="flex justify-center">
    <!-- Create Task button -->
    <a href='create' class="mt-4 relative inline-flex items-center justify-center p-0.5 mb-2 me-2 overflow-hidden text-sm font-medium text-white rounded-lg group bg-gradient-to-br from-purple-600 to-blue-500 group-hover:from-purple-600 group-hover:to-blue-500 hover:text-white focus:ring-4 focus:outline-none focus:ring-blue-800">
        <span class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-gray-900 rounded-md group-hover:bg-opacity-0">
            Create Task
        </span>
    </a>
</div>