<h2 class="flex flex-row flex-nowrap items-center mt-16 uppercase">
    <span class="flex-grow block border-t border-purple-700"></span>
    <span class="flex-none block mx-4 px-4 py-2.5 text-xl rounded leading-none font-medium bg-gray-900 text-white">
        You're editing task Nº <?php echo $this->taskData['id']; ?>
    </span>
    <span class="flex-grow block border-t border-purple-700"></span>
</h2>

<div class="relative overflow-x-auto shadow-md sm:rounded-lg border-2 border-purple-700 bg-gray-700 mt-16 sm:w-full md:w-1/2 lg:w-1/3 xl:w-[600px] mx-auto">
    <form action="update" method="post" class="max-w-sm mx-auto mt-8 mb-8">
        <input type="hidden" id="id" name="id" value="<?php echo $this->taskData['id']; ?>">
        <div class="mb-5">
            <label for="name" class="block mb-1 text-sm font-medium text-white">Name:</label>
            <input type="text" id="name" name="name" class="text-sm rounded-lg block w-full p-2 dark:bg-gray-900 dark:text-white" value="<?php echo $this->taskData['name']; ?>" required />
        </div>
        <div class="mb-5">
            <label for="status" class="block mb-1 text-sm font-medium text-white">Status:</label>
            <input type="text" id="status" name="status" class="text-sm rounded-lg block w-full p-2 dark:bg-gray-900 dark:text-white" value="<?php echo $this->taskData['status']; ?>" required />
        </div>
        <div class="mb-5">
            <label for="dateTimeStarted" class="block mb-1 text-sm font-medium text-white">Start Date:</label>
            <input type="datetime-local" id="dateTimeStarted" name="dateTimeStarted" class="text-sm rounded-lg block w-full p-2 dark:bg-gray-900 dark:text-white" value="<?php echo $this->taskData['dateTimeStarted']; ?>" required />
        </div>
        <div class="mb-5">
            <label for="dateTimeFinished" class="block mb-1 text-sm font-medium text-white">Finish Date::</label>
            <input type="datetime-local" id="dateTimeFinished" name="dateTimeFinished" class="text-sm rounded-lg block w-full p-2 dark:bg-gray-900 dark:text-white" value="<?php echo $this->taskData['dateTimeFinished']; ?>" required />
        </div>
        <div class="mb-5">
            <label for="user" class="block mb-1 text-sm font-medium text-white">User:</label>
            <input type="text" id="user" name="user" class="text-sm rounded-lg block w-full p-2 dark:bg-gray-900 dark:text-white" value="<?php echo $this->taskData['user']; ?>" required />
        </div>

        <div class="flex justify-between mt-5">
            <!-- Return button -->
            <a href="/web" class="relative inline-flex items-center justify-center p-0.5 overflow-hidden text-sm font-medium text-white rounded-lg group bg-gradient-to-br from-purple-600 to-blue-500 group-hover:from-purple-600 group-hover:to-blue-500 hover:text-white focus:ring-4 focus:outline-none focus:ring-blue-800">
                <span class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-gray-900 rounded-md group-hover:bg-opacity-0">
                    Return
                </span>
            </a>
            <!-- Update button -->
            <span class="relative inline-flex items-center justify-center p-0.5 overflow-hidden text-sm font-medium text-white rounded-lg group bg-gradient-to-br from-purple-600 to-blue-500 group-hover:from-purple-600 group-hover:to-blue-500 hover:text-white focus:ring-4 focus:outline-none focus:ring-blue-800">
                <input type="submit" value="Update" class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-gray-900 rounded-md group-hover:bg-opacity-0">
            </span>
        </div>
    </form>
</div>