<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<script src="https://cdn.tailwindcss.com"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
	<script src="../web/javascripts/deleteConfirmation.js"></script>
	
</head>

<body class="dark bg-gray-200">
	<div class="container mx-auto px-4 max-w-screen-lg">
		<?php echo $this->content(); ?>
	</div>
</body>

</html>